MQTT_BROKER_ADDRESS = '' # Address of MQTT broker
MQTT_BROKER_PORT = 1883 # Port of MQTT broker
MONITOR_HEARTBEAT_MINUTES = 5
MONITOR_WATER_TEMPERATURE_ENABLED = True # Monitor DS18B20
MONITOR_WATER_TEMPERATURE_POLLING_SECONDS = 10 # How frequently to check the temperature
MONITOR_DHT22_ENABLED = True # Monitor DHT22
MONITOR_DHT22_POLLING_SECONDS = 10 # How frequently to check the DHT22 Sensor